apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nestjs-server
  template:
    metadata:
      labels:
        component: nestjs-server
    spec:
      containers:
        - name: nestjs-server
          image: zycienakodach/starwars-eventsourcing-nestjs-server
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_MODE
              value: typeorm
            - name: DATABASE_HOST
              value: postgres-cluster-ip-service
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
              #valueFrom:
              #  secretKeyRef:
              #    name: pgpassword
              #    key: PGPASSWORD
